name = "Mockwyrmzardry"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3952a8aaf34c84d2ae9a75aca1a55905a49f0bcf9fca5a39e24247401dcf31e8"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
