name = "Mockwyrmzardy"
author = "Egassy"
version = "3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4d1739bbf0c5c77195ebab8ef9885a183b3339013e74a3c3987efa70fbbd219"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
unsup = "1.2.7"
