name = "Mockwyrmzardry"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f0c327c55a3701df20d94e985225bd7bb86a73a73690c99d598b3160c37237c"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
