name = "Mockwrymzardry"
author = "Egassy"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8d5c2737ec9a393188787b0f6dbfa477aab7fc851da695cc908472eb6482de6"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
