name = "Mockwyrmzardy"
author = "Egassy"
version = "3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c444b76b10f57375aecdbd5427d9000847550a0bd076753cc6788babb0edca2a"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
unsup = "1.2.7"
