name = "Mockwyrmzardry"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "480aeec0d0aeb3336ec0915148703277c0cbd5c810f44345bd754a829aa0468b"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
